# Generated by Django 3.0.7 on 2020-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_admin', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.TextField(),
        ),
    ]
